import Head from "next/head";
import Image from "next/image";

import { getSession } from "next-auth/react";
// import { client } from "../client";
import { useSession, signIn, signOut } from "next-auth/react";
import Home from "../components/Home";
import Header from "../components/Header";
import Products from "../components/Products";
import Footer from "../components/Footer";
import { client } from "../lib/client";
const data = [
  {
    _id: 1,
    name: " Banana",
    image: "/assets/banana.jpg",
    price: "Ksh 50",
    slug: "banana",
  },
  {
    _id: 2,
    name: "Apple",
    image: "/assets/apple.jpg",
    price: "Ksh 10",
    slug: "apple",
  },
  {
    _id: 3,
    name: "Tomato",
    image: "/assets/tomato.jpg",
    price: "Ksh 20",
    slug: "tomato",
  },
  {
    _id: 4,
    name: "Pineapple",
    image: "/assets/pieapple.jpg",
    price: "Ksh 80",
    slug: "pineapple",
  },
  {
    _id: 5,
    name: "Ovacado",
    image: "/assets/ovacado.jpg",
    price: "Ksh 75",
    slug: "ovacado",
  },
  {
    _id: 6,
    name: "Orange",
    image: "/assets/orange.jpg",
    price: "Ksh 60",
    slug: "fruit",
  },
];
export default function App({products}) {
  // console.log(products)

    return (
      <div className=" bg-gray-100 ">
        <Head>
          <title>Civrot Store</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Home />
          <div className="flex items-center justify-evenly py-4">
              <div>
                <h2 className="text-2xl font-bold">Best seller</h2>
              </div>
              <div>
                <button className="font-medium">View All</button>
              </div>
            </div>
          <div className="grid grid-cols-2 space-x-4 space-y-4  md:grid-cols-4">

            {products.map((product) => (
              <>
              <Products key={product._id} product={product} />
              </>
            ))}
          </div>
          <Footer />
        </main>
      </div>
    );

}
export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);
  

  return {
    props: { products },
  };
};
