import Head from "next/head";
import Image from "next/image";

import { getSession } from "next-auth/react";
// import { client } from "../client";
import { useSession, signIn, signOut } from "next-auth/react";
import Home from "../components/Home";
import Header from "../components/Header";
import Products from "../components/Products";
import Footer from "../components/Footer";
import { client } from "../lib/client";
import { useState } from "react";
const data = [
  {
    _id: 1,
    name: " Banana",
    image: "/assets/banana.jpg",
    price: "Ksh 50",
    slug: "banana",
  },
  {
    _id: 2,
    name: "Apple",
    image: "/assets/apple.jpg",
    price: "Ksh 10",
    slug: "apple",
  },
  {
    _id: 3,
    name: "Tomato",
    image: "/assets/tomato.jpg",
    price: "Ksh 20",
    slug: "tomato",
  },
  {
    _id: 4,
    name: "Pineapple",
    image: "/assets/pieapple.jpg",
    price: "Ksh 80",
    slug: "pineapple",
  },
  {
    _id: 5,
    name: "Ovacado",
    image: "/assets/ovacado.jpg",
    price: "Ksh 75",
    slug: "ovacado",
  },
  {
    _id: 6,
    name: "Orange",
    image: "/assets/orange.jpg",
    price: "Ksh 60",
    slug: "fruit",
  },
];
export default function App({ products, uniques, juicy, bests }) {
  const [category, setCategory] = useState("");
  console.log(uniques);

  return (
    <div className=" bg-gray-100 ">
      <Head>
        <title>Civrot Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Home />
        <div className="flex items-center justify-evenly py-4">
          <div>
            <h2 className="text-2xl font-bold">Awesome Fruits</h2>
          </div>
          <div>
            <button className="font-medium">View All</button>
          </div>
        </div>
        <div className="flex flex-col justify-center items-center">
          Best Selling
          <div className="grid pb-4 justify-center place-items-center grid-cols-2 space-x-1 space-y-3  md:grid-cols-4">
            {bests.map((product) => (
              <>
                <Products key={product._id} product={product} />
              </>
            ))}
          </div>
        </div>
        <div className="flex flex-col justify-center items-center">
          Unique Fruits
          <div className="grid pb-4 justify-center place-items-center grid-cols-2 space-x-1 space-y-3  md:grid-cols-4">
            {uniques.map((product) => (
              <>
                <Products key={product._id} product={product} />
              </>
            ))}
          </div>
        </div>
        <div className="flex flex-col justify-center items-center">
          Juicy Fruits
          <div className="grid pb-4 justify-center place-items-center grid-cols-2 space-x-1 space-y-3  md:grid-cols-4">
            {juicy.map((product) => (
              <>
                <Products key={product._id} product={product} />
              </>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const category1 =
    '*[_type == "product" && references("f9b2c4fc-8868-46cd-933c-2a2b3addf592")] ';
  const bests = await client.fetch(category1);
  const category2 =
    '*[_type == "product" && references("58a90eea-1d00-4c07-9a7d-570251c513ee")] ';
  const uniques = await client.fetch(category2);
  const category3 =
    '*[_type == "product" && references("9bb78bdc-8824-42cf-bb52-bc1df3fb7b61")] ';
  const juicy = await client.fetch(category3);

  return {
    props: { products, uniques, juicy, bests },
  };
};
